[package]
name = "veil-relay"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
anyhow.workspace = true
base64.workspace = true
tokio.workspace = true

axum = { version = "0.8", features = ["ws"] }
ed25519-dalek = "2"
dashmap = "6"
tracing = "0.1"
tracing-subscriber = "0.3"
